/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage the homepage content. The homepage is designed to communicate value in under 3 seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Add and arrange sections for the homepage. Start with a Hero block.
   */
  sections?:
    | (
        | {
            /**
             * Small text above the headline (e.g., "Discovery-First Product Management")
             */
            eyebrow?: string | null;
            /**
             * Main headline. Action-oriented, no jargon. Must pass the "so what" test in 3 seconds.
             */
            headline: string;
            /**
             * Word to highlight in the headline (will be styled with accent color)
             */
            headlineEmphasisWord?: string | null;
            /**
             * Expands on headline. Plain English value prop.
             */
            subheadline: string;
            /**
             * Optional proof point or additional context.
             */
            supportingText?: string | null;
            /**
             * e.g., "Start Free Trial"
             */
            primaryCtaText: string;
            /**
             * Valid internal path or URL
             */
            primaryCtaUrl: string;
            /**
             * e.g., "See How It Works"
             */
            secondaryCtaText?: string | null;
            /**
             * Valid internal path or URL
             */
            secondaryCtaUrl?: string | null;
            /**
             * Product screenshot or illustration. Shows the product, not stock photography.
             */
            image: number | Media;
            /**
             * Small trust signal below CTAs (e.g., "No credit card required")
             */
            trustNote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Controls the visual style of the CTA section
             */
            variant?: ('standard' | 'compact' | 'final') | null;
            /**
             * Display large logo mark above headline (typically for final CTA)
             */
            showLogoMark?: boolean | null;
            /**
             * Strong, transformation-focused headline. Reinforce core value.
             */
            headline: string;
            /**
             * Optional supporting text or final nudge.
             */
            subheadline?: string | null;
            /**
             * Action verb + outcome (e.g., "Start Free Trial")
             */
            primaryCtaText: string;
            /**
             * Usually signup or trial
             */
            primaryCtaUrl: string;
            /**
             * Alternative action (e.g., "Book a Demo")
             */
            secondaryCtaText?: string | null;
            /**
             * Demo or contact page
             */
            secondaryCtaUrl?: string | null;
            /**
             * Display trust signals below the CTAs
             */
            showTrustSignals?: boolean | null;
            /**
             * Reduce friction with trust signals (e.g., "No credit card required")
             */
            trustSignals?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional extra context below the CTA buttons
             */
            additionalMessage?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * How to display the testimonial(s)
             */
            variant?: ('single' | 'multiple' | 'with_metrics') | null;
            /**
             * e.g., "Teams Who've Made the Shift" or "What Product Teams Say"
             */
            headline?: string | null;
            /**
             * Quality over quantity. Specific outcomes beat generic praise.
             */
            quotes: {
              /**
               * The testimonial text. Must include specific outcome, not generic praise.
               */
              quote: string;
              /**
               * Optional context for the quote (e.g., "After 3 months using Shorter Loop")
               */
              context?: string | null;
              authorName: string;
              /**
               * Role and company
               */
              authorTitle: string;
              /**
               * Headshot (increases trust significantly)
               */
              authorImage?: (number | null) | Media;
              companyLogo?: (number | null) | Media;
              /**
               * Optional 1-5 star rating
               */
              rating?: number | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            /**
             * How to display the metrics
             */
            variant?: ('bar' | 'grid' | 'cards') | null;
            /**
             * Optional headline above the metrics
             */
            headline?: string | null;
            /**
             * Optional supporting text
             */
            subheadline?: string | null;
            /**
             * Each stat must include a concrete number, percentage, or timeframe
             */
            stats: {
              /**
               * e.g., "80%", "3x", "12 weeks", "40%"
               */
              value: string;
              /**
               * What the metric measures
               */
              label: string;
              /**
               * Optional additional context for the metric
               */
              context?: string | null;
              /**
               * Give this stat visual emphasis (accent color)
               */
              highlighted?: boolean | null;
              id?: string | null;
            }[];
            /**
             * Optional source for the stats (e.g., "Based on customer surveys Q3 2024")
             */
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metrics';
          }
        | {
            /**
             * How to display the workflow steps
             */
            variant?: ('flow_line' | 'numbered' | 'cards' | 'timeline') | null;
            /**
             * Small text above the headline (e.g., "How It Works")
             */
            eyebrow?: string | null;
            /**
             * Section headline (e.g., "From Noise to Strategy")
             */
            headline: string;
            /**
             * Brief setup text
             */
            subheadline?: string | null;
            /**
             * The workflow steps (3-6 steps recommended)
             */
            steps: {
              stepNumber: number;
              /**
               * Short label (e.g., "Signals", "Themes", "Opportunities")
               */
              label: string;
              /**
               * What happens at this stage
               */
              description: string;
              /**
               * Icon to display for this step
               */
              icon?:
                | (
                    | 'signal'
                    | 'theme'
                    | 'opportunity'
                    | 'bet'
                    | 'roadmap'
                    | 'outcome'
                    | 'collect'
                    | 'analyze'
                    | 'decide'
                    | 'execute'
                    | 'measure'
                    | 'learn'
                  )
                | null;
              /**
               * Give this step visual emphasis (accent color)
               */
              isPivotPoint?: boolean | null;
              /**
               * Optional screenshot showing this step in action
               */
              screenshot?: (number | null) | Media;
              id?: string | null;
            }[];
            /**
             * Optional wrap-up text after the steps
             */
            conclusion?: string | null;
            /**
             * Optional diagram or illustration of the full workflow
             */
            visual?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'workflow';
          }
        | {
            /**
             * How to display the pain points
             */
            variant?: ('list' | 'cards' | 'narrative' | 'warnings') | null;
            /**
             * Name the struggle. Can be provocative.
             */
            headline: string;
            /**
             * Optional elaboration (will be italicized)
             */
            subheadline?: string | null;
            /**
             * The story. Prose, not bullets. Should include antagonist + loss. Use for "narrative" variant.
             */
            narrative?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * List of pain points (3-4 recommended for most contexts)
             */
            painPoints: {
              /**
               * The pain in one line
               */
              title: string;
              /**
               * Expand the pain. Be specific, not generic.
               */
              description: string;
              icon?:
                | (
                    | 'warning'
                    | 'error'
                    | 'time'
                    | 'money'
                    | 'confusion'
                    | 'disconnect'
                    | 'chaos'
                    | 'silence'
                    | 'conflict'
                    | 'loss'
                  )
                | null;
              /**
               * For warning signs variant - indicates progression
               */
              severity?: ('early' | 'mid' | 'late') | null;
              /**
               * What happens because of this pain point
               */
              consequence?: string | null;
              id?: string | null;
            }[];
            /**
             * The question they ask themselves (e.g., "How do I justify this to the board?")
             */
            emotionalQuestion?: string | null;
            /**
             * The villains (behaviors, not people)
             */
            antagonists?:
              | {
                  /**
                   * e.g., "Loudest-voice wins"
                   */
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * What's at stake
             */
            losses?:
              | {
                  /**
                   * e.g., "6 months building the wrong feature"
                   */
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'painPoints';
          }
        | {
            /**
             * How to display the transformation
             */
            variant?: ('side_by_side' | 'stacked' | 'timeline' | 'compact') | null;
            /**
             * e.g., "The Pivot"
             */
            eyebrow?: string | null;
            /**
             * e.g., "From chaos to clarity"
             */
            headline: string;
            /**
             * e.g., "Every transformation flows through the pivot."
             */
            subheadline?: string | null;
            /**
             * e.g., "The Status Quo"
             */
            beforeColumnLabel?: string | null;
            /**
             * e.g., "With Shorter Loop"
             */
            afterColumnLabel?: string | null;
            /**
             * Before → After pairs (4-6 recommended)
             */
            transformations: {
              /**
               * Problem state
               */
              beforeTitle: string;
              /**
               * Solution state
               */
              afterTitle: string;
              /**
               * Expanded pain
               */
              beforeDetail?: string | null;
              /**
               * Expanded outcome
               */
              afterDetail?: string | null;
              id?: string | null;
            }[];
            /**
             * Display statistics that reinforce the pain/transformation
             */
            showStatsBar?: boolean | null;
            /**
             * Stats that reinforce the transformation with data
             */
            stats?:
              | {
                  /**
                   * e.g., "80%"
                   */
                  value: string;
                  /**
                   * e.g., "of features go unused"
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional: How Shorter Loop fits as the operating system for product decisions
             */
            positioningStatement?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'transformation';
          }
        | {
            /**
             * How to display the integrations
             */
            variant?: ('grouped' | 'grid' | 'compact') | null;
            /**
             * e.g., "Works With Your Stack" or "25+ Integrations. One Hub."
             */
            headline: string;
            /**
             * Address the fear (e.g., "Keep using Jira. We'll handle the rest.")
             */
            subheadline: string;
            /**
             * Group integrations by category
             */
            integrationGroups: {
              /**
               * e.g., "Issue Trackers", "Support Tools", "Analytics"
               */
              groupName: string;
              integrations: {
                name: string;
                status: 'live' | 'coming_soon' | 'beta';
                /**
                 * Highlight this integration
                 */
                featured?: boolean | null;
                logo: number | Media;
                /**
                 * Optional one-liner about what this integration does
                 */
                description?: string | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            /**
             * Other ways to integrate (API, CSV, etc.)
             */
            additionalMethods?:
              | {
                  /**
                   * e.g., "REST API", "CSV Import", "Webhooks"
                   */
                  title: string;
                  description: string;
                  icon?: ('api' | 'csv' | 'webhook' | 'zapier' | 'code') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * e.g., "See All Integrations"
             */
            ctaText?: string | null;
            /**
             * Link to full integrations page
             */
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'integrations';
          }
        | {
            /**
             * How to display the related content
             */
            variant?: ('cards' | 'list' | 'compact') | null;
            /**
             * e.g., "Continue Learning" or "Related Resources"
             */
            headline?: string | null;
            /**
             * Display a prominent next action for the user
             */
            showNextStep?: boolean | null;
            /**
             * The main recommended action for the reader
             */
            nextStep?: {
              /**
               * e.g., "Watch the 3-minute demo"
               */
              label: string;
              url: string;
              type: 'demo_video' | 'documentation' | 'template' | 'guide' | 'trial';
              /**
               * Brief description of what they'll get
               */
              description?: string | null;
            };
            /**
             * Links to related content (capabilities, articles, etc.)
             */
            relatedItems?:
              | {
                  title: string;
                  url: string;
                  /**
                   * How this content relates to the current page
                   */
                  relationshipType?: ('works_with' | 'alternative_to' | 'builds_on' | 'feeds_into' | 'related') | null;
                  contentType?: ('capability' | 'use_case' | 'blog' | 'guide' | 'case_study' | 'template') | null;
                  /**
                   * Brief description or why it's relevant
                   */
                  description?: string | null;
                  /**
                   * Optional thumbnail image
                   */
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedContent';
          }
        | {
            /**
             * e.g., "Frequently Asked Questions"
             */
            headline: string;
            /**
             * More questions is better for SEO (6-15 recommended)
             */
            questions: {
              /**
               * Natural language question matching real search queries
               */
              question: string;
              /**
               * Comprehensive answer. Schema-eligible answers need 150+ characters for rich snippets.
               */
              answer: string;
              /**
               * Optional grouping
               */
              category?: ('general' | 'technical' | 'pricing' | 'security') | null;
              /**
               * Include in FAQ schema markup for rich snippets?
               */
              schemaEligible?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * e.g., "Feedback Manager vs. Traditional Tools"
             */
            headline: string;
            /**
             * Frame the comparison
             */
            subheadline?: string | null;
            /**
             * Compare against categories or named competitors
             */
            comparisonType: 'category' | 'specific';
            /**
             * Comparison columns (your product + competitors/alternatives)
             */
            columns: {
              /**
               * e.g., "Short Loop", "Spreadsheets", "Generic PM Tools"
               */
              name: string;
              /**
               * Check if this column represents your product (for styling)
               */
              isSelf?: boolean | null;
              id?: string | null;
            }[];
            /**
             * Features/criteria being compared
             */
            rows: {
              /**
               * What's being compared
               */
              feature: string;
              /**
               * Value for each column (must match number of columns)
               */
              values: {
                /**
                 * Which column (0, 1, or 2)
                 */
                columnIndex: number;
                /**
                 * Can include ✓/✗ or be descriptive
                 */
                value: string;
                highlight?: boolean | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            /**
             * Optional wrap-up statement
             */
            conclusion?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparisonTable';
          }
        | {
            /**
             * e.g., "Built for Teams That Listen"
             */
            headline: string;
            /**
             * Optional framing
             */
            subheadline?: string | null;
            /**
             * Primary features shown prominently (2-3)
             */
            heroFeatures: {
              title: string;
              /**
               * One-line value prop
               */
              tagline: string;
              /**
               * Detailed explanation
               */
              description: string;
              benefits: {
                /**
                 * Single benefit (outcome, not specification)
                 */
                text: string;
                id?: string | null;
              }[];
              /**
               * Screenshot or illustration
               */
              image: number | Media;
              id?: string | null;
            }[];
            /**
             * Secondary features shown smaller (0-6)
             */
            additionalFeatures?:
              | {
                  title: string;
                  /**
                   * One-line value prop
                   */
                  tagline: string;
                  /**
                   * Brief explanation
                   */
                  description: string;
                  icon:
                    | 'collect'
                    | 'organize'
                    | 'analyze'
                    | 'prioritize'
                    | 'track'
                    | 'report'
                    | 'integrate'
                    | 'automate'
                    | 'collaborate'
                    | 'secure';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            /**
             * e.g., "Powered By" or "Built With"
             */
            headline: string;
            /**
             * Optional context
             */
            subheadline?: string | null;
            /**
             * Capabilities that power this solution (2-4)
             */
            capabilities: {
              /**
               * URL slug of the capability page
               */
              capabilitySlug: string;
              /**
               * e.g., "Feedback Manager", "Signals Engine"
               */
              capabilityName: string;
              /**
               * Why this capability matters here
               */
              roleInSolution: string;
              icon?:
                | ('feedback' | 'signals' | 'roadmap' | 'ost' | 'analytics' | 'insights' | 'workflow' | 'collaboration')
                | null;
              id?: string | null;
            }[];
            /**
             * Optional call to action
             */
            ctaText?: string | null;
            /**
             * Link to capabilities overview page
             */
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilityLinks';
          }
        | {
            /**
             * e.g., "How Teams Use Feedback Manager"
             */
            headline: string;
            /**
             * Optional framing
             */
            subheadline?: string | null;
            /**
             * Different scenarios or personas (2-4)
             */
            useCases: {
              /**
               * Scenario title, e.g., "SaaS Product Team"
               */
              title: string;
              /**
               * Context, e.g., "500+ backlog items"
               */
              subtitle?: string | null;
              /**
               * e.g., "B2B SaaS, 25-person team"
               */
              companyType?: string | null;
              /**
               * The problem they faced
               */
              challenge: string;
              /**
               * How they used the capability
               */
              solution: string;
              /**
               * Outcomes achieved. At least one must have a metric!
               */
              results: {
                /**
                 * Single result statement
                 */
                text: string;
                /**
                 * Does this result include a number/percentage/timeframe?
                 */
                hasMetric: boolean;
                id?: string | null;
              }[];
              showQuote?: boolean | null;
              quote?: {
                text: string;
                authorName: string;
                /**
                 * Role and company
                 */
                authorTitle: string;
              };
              /**
               * Optional visual
               */
              image?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'useCases';
          }
      )[]
    | null;
  /**
   * Page title for search engines. Include primary keyword near the front. (50-60 characters)
   */
  metaTitle?: string | null;
  /**
   * Page description for search engines. Should be compelling with problem + promise. (150-160 characters)
   */
  metaDescription?: string | null;
  /**
   * Primary and secondary keywords for SEO tracking (not used by Google, but useful for internal reference)
   */
  metaKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Image for social media sharing (1200x630px recommended)
   */
  ogImage?: (number | null) | Media;
  /**
   * Only set if this page should point to a different canonical URL
   */
  canonicalUrl?: string | null;
  /**
   * Prevent search engines from indexing this page
   */
  noIndex?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineEmphasisWord?: T;
              subheadline?: T;
              supportingText?: T;
              primaryCtaText?: T;
              primaryCtaUrl?: T;
              secondaryCtaText?: T;
              secondaryCtaUrl?: T;
              image?: T;
              trustNote?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              variant?: T;
              showLogoMark?: T;
              headline?: T;
              subheadline?: T;
              primaryCtaText?: T;
              primaryCtaUrl?: T;
              secondaryCtaText?: T;
              secondaryCtaUrl?: T;
              showTrustSignals?: T;
              trustSignals?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              additionalMessage?: T;
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              variant?: T;
              headline?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    context?: T;
                    authorName?: T;
                    authorTitle?: T;
                    authorImage?: T;
                    companyLogo?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    context?: T;
                    highlighted?: T;
                    id?: T;
                  };
              source?: T;
              id?: T;
              blockName?: T;
            };
        workflow?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              steps?:
                | T
                | {
                    stepNumber?: T;
                    label?: T;
                    description?: T;
                    icon?: T;
                    isPivotPoint?: T;
                    screenshot?: T;
                    id?: T;
                  };
              conclusion?: T;
              visual?: T;
              id?: T;
              blockName?: T;
            };
        painPoints?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              narrative?: T;
              painPoints?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    severity?: T;
                    consequence?: T;
                    id?: T;
                  };
              emotionalQuestion?: T;
              antagonists?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              losses?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        transformation?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              beforeColumnLabel?: T;
              afterColumnLabel?: T;
              transformations?:
                | T
                | {
                    beforeTitle?: T;
                    afterTitle?: T;
                    beforeDetail?: T;
                    afterDetail?: T;
                    id?: T;
                  };
              showStatsBar?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              positioningStatement?: T;
              id?: T;
              blockName?: T;
            };
        integrations?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              integrationGroups?:
                | T
                | {
                    groupName?: T;
                    integrations?:
                      | T
                      | {
                          name?: T;
                          status?: T;
                          featured?: T;
                          logo?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              additionalMethods?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        relatedContent?:
          | T
          | {
              variant?: T;
              headline?: T;
              showNextStep?: T;
              nextStep?:
                | T
                | {
                    label?: T;
                    url?: T;
                    type?: T;
                    description?: T;
                  };
              relatedItems?:
                | T
                | {
                    title?: T;
                    url?: T;
                    relationshipType?: T;
                    contentType?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              headline?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    category?: T;
                    schemaEligible?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparisonTable?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              comparisonType?: T;
              columns?:
                | T
                | {
                    name?: T;
                    isSelf?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    feature?: T;
                    values?:
                      | T
                      | {
                          columnIndex?: T;
                          value?: T;
                          highlight?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              conclusion?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              heroFeatures?:
                | T
                | {
                    title?: T;
                    tagline?: T;
                    description?: T;
                    benefits?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    image?: T;
                    id?: T;
                  };
              additionalFeatures?:
                | T
                | {
                    title?: T;
                    tagline?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilityLinks?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              capabilities?:
                | T
                | {
                    capabilitySlug?: T;
                    capabilityName?: T;
                    roleInSolution?: T;
                    icon?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        useCases?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              useCases?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    companyType?: T;
                    challenge?: T;
                    solution?: T;
                    results?:
                      | T
                      | {
                          text?: T;
                          hasMetric?: T;
                          id?: T;
                        };
                    showQuote?: T;
                    quote?:
                      | T
                      | {
                          text?: T;
                          authorName?: T;
                          authorTitle?: T;
                        };
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  ogImage?: T;
  canonicalUrl?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}