/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage the homepage content. The homepage is designed to communicate value in under 3 seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Add and arrange sections for the homepage. Start with a Hero block.
   */
  sections?:
    | (
        | {
            /**
             * Small text above the headline (e.g., "Discovery-First Product Management")
             */
            eyebrow?: string | null;
            /**
             * Main headline. Action-oriented, no jargon. Must pass the "so what" test in 3 seconds.
             */
            headline: string;
            /**
             * Word to highlight in the headline (will be styled with accent color)
             */
            headlineEmphasisWord?: string | null;
            /**
             * Expands on headline. Plain English value prop.
             */
            subheadline: string;
            /**
             * Optional proof point or additional context.
             */
            supportingText?: string | null;
            /**
             * e.g., "Start Free Trial"
             */
            primaryCtaText: string;
            /**
             * Valid internal path or URL
             */
            primaryCtaUrl: string;
            /**
             * e.g., "See How It Works"
             */
            secondaryCtaText?: string | null;
            /**
             * Valid internal path or URL
             */
            secondaryCtaUrl?: string | null;
            /**
             * Product screenshot or illustration. Shows the product, not stock photography.
             */
            image: number | Media;
            /**
             * Small trust signal below CTAs (e.g., "No credit card required")
             */
            trustNote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Controls the visual style of the CTA section
             */
            variant?: ('standard' | 'compact' | 'final') | null;
            /**
             * Display large logo mark above headline (typically for final CTA)
             */
            showLogoMark?: boolean | null;
            /**
             * Strong, transformation-focused headline. Reinforce core value.
             */
            headline: string;
            /**
             * Optional supporting text or final nudge.
             */
            subheadline?: string | null;
            /**
             * Action verb + outcome (e.g., "Start Free Trial")
             */
            primaryCtaText: string;
            /**
             * Usually signup or trial
             */
            primaryCtaUrl: string;
            /**
             * Alternative action (e.g., "Book a Demo")
             */
            secondaryCtaText?: string | null;
            /**
             * Demo or contact page
             */
            secondaryCtaUrl?: string | null;
            /**
             * Display trust signals below the CTAs
             */
            showTrustSignals?: boolean | null;
            /**
             * Reduce friction with trust signals (e.g., "No credit card required")
             */
            trustSignals?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional extra context below the CTA buttons
             */
            additionalMessage?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * How to display the testimonial(s)
             */
            variant?: ('single' | 'multiple' | 'with_metrics') | null;
            /**
             * e.g., "Teams Who've Made the Shift" or "What Product Teams Say"
             */
            headline?: string | null;
            /**
             * Quality over quantity. Specific outcomes beat generic praise.
             */
            quotes: {
              /**
               * The testimonial text. Must include specific outcome, not generic praise.
               */
              quote: string;
              /**
               * Optional context for the quote (e.g., "After 3 months using Shorter Loop")
               */
              context?: string | null;
              authorName: string;
              /**
               * Role and company
               */
              authorTitle: string;
              /**
               * Headshot (increases trust significantly)
               */
              authorImage?: (number | null) | Media;
              companyLogo?: (number | null) | Media;
              /**
               * Optional 1-5 star rating
               */
              rating?: number | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            /**
             * How to display the metrics
             */
            variant?: ('bar' | 'grid' | 'cards') | null;
            /**
             * Optional headline above the metrics
             */
            headline?: string | null;
            /**
             * Optional supporting text
             */
            subheadline?: string | null;
            /**
             * Each stat must include a concrete number, percentage, or timeframe
             */
            stats: {
              /**
               * e.g., "80%", "3x", "12 weeks", "40%"
               */
              value: string;
              /**
               * What the metric measures
               */
              label: string;
              /**
               * Optional additional context for the metric
               */
              context?: string | null;
              /**
               * Give this stat visual emphasis (accent color)
               */
              highlighted?: boolean | null;
              id?: string | null;
            }[];
            /**
             * Optional source for the stats (e.g., "Based on customer surveys Q3 2024")
             */
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metrics';
          }
      )[]
    | null;
  /**
   * Page title for search engines. Include primary keyword near the front. (50-60 characters)
   */
  metaTitle?: string | null;
  /**
   * Page description for search engines. Should be compelling with problem + promise. (150-160 characters)
   */
  metaDescription?: string | null;
  /**
   * Primary and secondary keywords for SEO tracking (not used by Google, but useful for internal reference)
   */
  metaKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Image for social media sharing (1200x630px recommended)
   */
  ogImage?: (number | null) | Media;
  /**
   * Only set if this page should point to a different canonical URL
   */
  canonicalUrl?: string | null;
  /**
   * Prevent search engines from indexing this page
   */
  noIndex?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineEmphasisWord?: T;
              subheadline?: T;
              supportingText?: T;
              primaryCtaText?: T;
              primaryCtaUrl?: T;
              secondaryCtaText?: T;
              secondaryCtaUrl?: T;
              image?: T;
              trustNote?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              variant?: T;
              showLogoMark?: T;
              headline?: T;
              subheadline?: T;
              primaryCtaText?: T;
              primaryCtaUrl?: T;
              secondaryCtaText?: T;
              secondaryCtaUrl?: T;
              showTrustSignals?: T;
              trustSignals?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              additionalMessage?: T;
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              variant?: T;
              headline?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    context?: T;
                    authorName?: T;
                    authorTitle?: T;
                    authorImage?: T;
                    companyLogo?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    context?: T;
                    highlighted?: T;
                    id?: T;
                  };
              source?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  ogImage?: T;
  canonicalUrl?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}